name: Build Debian packages

on:
  release:
    types: [published]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get install -y \
            devscripts debhelper dpkg-dev fakeroot gcc pkgconf \
            libasound2-dev
            
          dpkg --add-architecture arm64
          
          apt-get update
          apt-get install -y \
            crossbuild-essential-arm64 \
            libc6:arm64 \
            libasound2t64:arm64 \
            libasound2-dev:arm64

      - name: Update changelog
        run: |
          VERSION=$(grep '^version' pyproject.toml | cut -d'"' -f2)
          export DEBFULLNAME="GitHub Actions"
          export DEBEMAIL="actions@github.com"
          dch --newversion "$VERSION" "Release $VERSION"

      - name: Build package
        run: |
          dpkg-buildpackage -us -uc -b -aarm64

      - name: Download soundfonts
        if: github.event_name == 'release'
        run: |
          curl -LO https://geekfunklabs.com/soundfonts_collection.tar.gz

      - name: Upload to release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ../*.deb
            soundfonts_collection.tar.gz
